### ISSUE TITLE
Errors building

### ISSUE THREAD

**Issue by krinkere** [alexholmes/hiped2#2]
I downloaded the code and try to build it. Seems like several jars are outdated already. For example, I had to fix kafka, and now ran into 

Failed to execute goal on project hip: Could not resolve dependencies for project hip:hip:jar:2.0.0: The following artifacts could not be resolved: com.linkedin.camus:camus-schema-registry:jar:0.1.0-SNAPSHOT, 

Please fix pom.xml

Thanks,
Al Krinker

**Comment by alexholmes** [comment]
Did you run "mvn validate" prior to running the build? See "Building your own distribution" at https://github.com/alexholmes/hiped2.

**Comment by krinkere** [comment]
Opps... I blindly ran mvm clean install thru Netbeans. Run mvm validate and everything worked perfectly. Careless mistake on my part. Thank you for your quick response!

Cheers,
Al
